### ISSUE TITLE
node_module install fail - Pre-build test failed

### ISSUE THREAD

**Issue by dealion** [imagemin/pngcrush-bin#16]
Mac 10.7.5
Node v5.10.1
NPM v3.8.6

Can't seem to overcome this one. Any insight would be appreciated.

> pngcrush-bin@3.0.0 postinstall /Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/pngcrush-bin
> node lib/install.js

  ⚠ The `/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/pngcrush-bin/vendor/pngcrush` binary doesn't seem to work correctly
  ⚠ pngcrush pre-build test failed
  ℹ compiling from source
  ✖ HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/got/index.js:192:24)
    at emitOne (events.js:90:13)
    at EventEmitter.emit (events.js:182:7)
    at Immediate._onImmediate (/Users/samiam/Sites/roots-example-project.com/site/web/app/themes/sage/node_modules/got/index.js:58:8)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by shinnn** [comment]
Just upgrade the OS. ref. https://github.com/imagemin/jpegtran-bin/issues/69#issuecomment-162008355

**Comment by shinnn** [comment]
Just upgrade the OS. ref. https://github.com/imagemin/jpegtran-bin/issues/69#issuecomment-162008355
